/* ----- DATA FOR FORCE LAYOUT ----- */
var links = [
    { source: "Anh văn 1", target: "Anh văn 2", type: "1" },
    { source: "Anh văn 2", target: "Anh văn 3", type: "1" },
    { source: "Anh văn 3", target: "Anh văn 4", type: "1" },
    { source: "Vật lý 1", target: "Vật lý 2", type: "1" },
    { source: "Vật lý 1", target: "Thí nghiệm vật lý", type: "2" },
    { source: "Vật lý 1", target: "Cơ ứng dụng", type: "1" },
    { source: "Giải tích 1", target: "Cơ ứng dụng", type: "1" },
    { source: "Đại số", target: "Cơ ứng dụng", type: "1" },
    { source: "Giải tích 1", target: "Phương pháp tính", type: "1" },
    { source: "Giải tích 1", target: "Xác suất thống kê", type: "1" },
    { source: "Giải tích 1", target: "Giải tích 2", type: "1" },
    { source: "Đại số", target: "Phương pháp tính", type: "1" },
    { source: "Đại số", target: "Xác suất thống kê", type: "1" },
    { source: "Nhập môn điện toán", target: "Kỹ thuật lập trình", type: "1" },
    { source: "Nguyên lý cơ bản chủ nghĩa Mác-Lênin", target: "Tư tưởng Hồ Chí Minh", type: "1" },
    { source: "Nguyên lý cơ bản chủ nghĩa Mác-Lênin", target: "Đường lối cách mạng Đảng Cộng Sản Việt Nam", type: "1" },
    { source: "Kiến trúc máy tính", target: "Hệ điều hành", type: "1" },
    { source: "Kỹ thuật lập trình", target: "Cấu trúc dữ liệu và giải thuật", type: "1" },
    { source: "Hệ thống số", target: "Kiến trúc máy tính", type: "1" },
    { source: "Thực tập tốt nghiệp", target: "Luận văn tốt nghiệp", type: "1" },
    { source: "Hệ cơ sở dữ liệu", target: "Hệ quản trị cơ sở dữ liệu", type: "1" },
    { source: "Hệ cơ sở dữ liệu", target: "Cơ sở dữ liệu phân tán, hướng đối tượng", type: "1" },
    { source: "Hệ cơ sở dữ liệu", target: "Thương mại điện tử", type: "1" },
    { source: "Hệ cơ sở dữ liệu", target: "Khai phá dữ liệu", type: "1" },
    { source: "Hệ cơ sở dữ liệu", target: "Bảo mật cho hệ thống thông tin", type: "1" },
    { source: "Kỹ thuật lập trình", target: "Công nghệ phần mềm", type: "1" },
    { source: "Hệ thống số", target: "Thiết kế luận lý với Verilog HDL", type: "1" },
    { source: "Hệ thống số", target: "Thực tập phần cứng máy tính", type: "1" },
    { source: "Thiết kế luận lý với Verilog HDL", target: "Đồ án Thiết kế luận lý ", type: "1" },
    { source: "Kiến trúc máy tính", target: "Vi xử lý - Vi điều khiển", type: "1" },
    { source: "Kiến trúc máy tính", target: "Thiết kế luận lý nâng cao", type: "1" },
    { source: "Ký năng chuyên nghiệp cho Kỹ sư", target: "Đồ án Kiến trúc máy tính", type: "1" },
    { source: "Kiến trúc máy tính", target: "Đánh giá hiệu năng hệ thống", type: "1" },
    { source: "Mạng máy tính ", target: "Đánh giá hiệu năng hệ thống", type: "1" },
    { source: "Kiến trúc máy tính", target: "Đánh giá hiệu năng hệ thống", type: "1" },
    { source: "Xác suất thồng kê", target: "Đánh giá hiệu năng hệ thống", type: "1" },
    { source: "Cấu trúc rời rạc cho KHMT", target: "Đánh giá hiệu năng hệ thống", type: "1" },
    { source: "Mạng máy tính", target: "Mạng máy tính nâng cao", type: "1" },
    { source: "Mạng máy tính", target: "Mật mã và an ninh mạng", type: "1" },
    { source: "Công nghệ phần mềm", target: "Quản lý dự án phần mềm", type: "1" },
    { source: "Cấu trúc dữ liệu và giải thuật", target: "Kiểm tra phần mềm", type: "1" },
    { source: "Cấu trúc dữ liệu và giải thuật", target: "Kiến trúc phần mềm", type: "1" },
    { source: "Cấu trúc dữ liệu và giải thuật", target: "Phát triển ứng dụng trên thiết bị di động", type: "1" },
    { source: "Đồ hoạ máy tính", target: "Lập trình game", type: "1" },
    { source: "Đồ hoạ máy tính", target: "Phát triển ứng dụng trên thiết bị di động", type: "1" },
    { source: "Nhập môn trí tuệ nhân tạo", target: "Xử lý ngôn ngữ tự nhiên", type: "1" },
    { source: "Nhập môn trí tuệ nhân tạo", target: "Hệ thống thông minh", type: "1" },
    { source: "Hệ điều hành", target: "Hệ thời gian thực", type: "1" },
    { source: "Công nghệ phần mềm", target: "Nhập môn trí tuệ nhân tạo", type: "1" },
    { source: "Cấu trúc dữ liệu và giải thuật", target: "Lập trình game", type: "1" }
];
    /*------------------------------------------- */
